---
- name: Install plugins.
  dnf:
    name: yum-utils
    state: present

- name: Install docker-ce repository.
  command: >
    dnf config-manager --add-repo
    https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Start Docker
  service: name='docker' state=started enabled=yes
