- hosts: all
  become: yes
  vars:
    - rsyslog_server: "192.168.56.132"

  roles:
    - role: certificate
      vars:
        - cert_dir_remote: "/opt/rsyslog_certs/"
        - cert_dir_local:  "certs/"
        - new_CA: false
      tags: cert
      
    - role: client
      vars:
        journal_conf: "/etc/systemd/journald.conf"
        journal_custom_conf: "/etc/systemd/journald.d/"
      tags: client

    - role: server 
      vars:
        - config_dir: /opt/rsyslog_server/
      tags: server

