- hosts: all
  become: yes

  roles:
    - role: client
      vars:
        journal_conf: "/etc/systemd/journald.conf"
        journal_custom_conf: "/etc/systemd/journald.d/"
        rsyslog_conf: "/etc/rsyslog.conf"
        rsyslog_server: "192.168.56.132"
      tags: client

    - role:  server 
      tags: server
        
    # - role: certificate
