---
- name: Disable SELinux.
  include_tasks: disable_selinux.yaml

- name: Get package information.
  package_facts:
    manager: auto

- name: Install Docker.
  include_tasks: docker.yaml
  when: "'docker-ce' not in ansible_facts.packages"

- name: Create a directory for Docker Compose and log storage.
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - /var/log/log_storage
    - /opt/rsyslog_server/Docker

- name: Copy certificates.
  copy:
    src:  "certs/{{ item.src }}"
    dest: "/etc/pki/rsyslog/{{ item.dst }}"
  loop:
    - {src: "{{ ansible_nodename }}-cert.pem",
       dst: rslserver-cert.pem}
    - {src: "{{ ansible_nodename }}-key.pem",
       dst: rslserver-key.pem}
    - {src: ca.pem, dst: ca.pem}

- name: Clone Docker Compose files.
  copy:
    src:  "roles/server/files/{{ item.src }}"
    dest: "{{ config_dir }}{{ item.dst }}"
  loop:
    - {src: docker-compose.yaml, dst: ''}
    - {src: Dockerfile,    dst: Docker}
    - {src: rsyslog.conf,  dst: Docker}    
    - {src: entrypoint.sh, dst: Docker}

# - name: Run Docker Compose.
#   shell: "docker compose --project-directory /opt/rsyslog_server up -d"
