---
- name: Install rsyslog
  dnf:
    name: 
    - rsyslog
    - rsyslog-gnutls
    - gnutls
    - gnutls-utils
    state: present

- name: Start and enable rsyslog
  service:
    name: rsyslog
    state: started 
    enabled: yes

- name: Create directory for journald configuration files
  file:
    state: directory
    path: '{{ journal_custom_conf }}'

- name: Create a custom journald configuration
  file:
    state: touch
    path: '{{ journal_custom_conf }}forward.conf'

- name: Write custom journald configuration
  copy:
    dest: '{{ journal_custom_conf }}forward.conf'
    content: |
      [Journal]
      ForwardToSyslog=yes
  register: journal_change

- name: Restart journald after configuration change
  service:
    name: 'systemd-journald'
    state: restarted
  when: journal_change.changed

- name: Copy certificates.
  copy:
    src:  "certs/{{ item }}"
    dest: /etc/pki/rsyslog
  loop:
    - "{{ ansible_nodename }}-cert.pem"
    - "{{ ansible_nodename }}-key.pem"
    - ca.pem

- name: Add rsyslog server info to configuration file
  copy:
    src: roles/client/files/tls.conf
    dest: /etc/rsyslog.d/tls.conf

- name: Restart rsyslog after configuration change
  service:
    name: 'rsyslog'
    state: restarted
